apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: flyt-isygraving-gateway
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: flyt-isygraving-gateway
    app.kubernetes.io/instance: flyt-isygraving-gateway_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-flyt-isygraving-gateway:latest
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  url:
    hostname: flyt.vigoiks.no
    basePath: ""
  ingress:
    enabled: true
    basePath: path
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx700M'
  envFrom:
    - secretRef:
        name: fint-flyt-file-oauth2-client
  resources:
    limits:
      memory: "750Mi"
      cpu: "500m"
    requests:
      memory: "512Mi"
      cpu: "100m"
  observability:
    metrics:
      enabled: true
      port: "8080"
      path: /actuator/prometheus
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }
